[datasets]
git-tree-sha1 = "c381ee8dda80556d3e2b5d27e1de92a943cd26f2"
lazy = true

    [[datasets.download]]
    sha256 = "eaa5c63ebe7cc2d882ed905cc353fbffd4bd38c65330301f8df9e3c473b8cff6"
    url = "https://github.com/dvillacis/TestDatasets/releases/download/v0.1.0-artifact/datasets_0.1.0.tar.gz"